import type { Order } from "@/types/order.types";

export const mockOrders: Order[] = [
  {
    id: "1051",
    code: "GW-1051",
    status: "por_confirmar",
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    etaMin: 40,
    customerName: "Ramiro Lopez",
    phone: "992113692",
    district: "San Borja",
    address: "Av. Javier Prado 2450",
    reference: "Frente a la estación",
    deliveryType: "delivery",
    deliveryFee: 10,
    total: 52.8,
    notes: "Sin cebolla en uno de los platos",
    items: [
      {
        id: "1051-1",
        name: "Chaufa Clásico",
        itemNameSnapshot: "Chaufa Clásico",
        qty: 2,
        unitPrice: 18.4,
        lineSubtotal: 36.8,
        extras: ["Ají aparte"],
      },
      {
        id: "1051-2",
        name: "Wantix",
        itemNameSnapshot: "Wantix",
        qty: 4,
        unitPrice: 1.5,
        lineSubtotal: 6,
        extras: [],
      },
    ],
  },
  {
    id: "1050",
    code: "GW-1050",
    status: "preparacion",
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    etaMin: 35,
    customerName: "Luciana Vega",
    phone: "987111222",
    district: "Surco",
    address: "Calle Los Álamos 410",
    reference: "Portón negro",
    deliveryType: "delivery",
    deliveryFee: 10,
    total: 43.9,
    notes: "Llamar al llegar",
    items: [
      {
        id: "1050-1",
        name: "Chaufa Aeropuerto",
        itemNameSnapshot: "Chaufa Aeropuerto",
        qty: 1,
        unitPrice: 30.9,
        lineSubtotal: 30.9,
        extras: ["Extra pollo", "Sillao aparte"],
      },
      {
        id: "1050-2",
        name: "Wantix",
        itemNameSnapshot: "Wantix",
        qty: 2,
        unitPrice: 1.5,
        lineSubtotal: 3,
        extras: [],
      },
    ],
  },
  {
    id: "1049",
    code: "GW-1049",
    status: "listo",
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    etaMin: 30,
    customerName: "María Fernanda",
    phone: "965444888",
    district: "Miraflores",
    address: "Av. Benavides 1880",
    reference: "Torre B, dpto. 602",
    deliveryType: "delivery",
    deliveryFee: 10,
    total: 61.5,
    notes: "Agregar cubiertos",
    items: [
      {
        id: "1049-1",
        name: "Chaufa Clásico",
        itemNameSnapshot: "Chaufa Clásico",
        qty: 3,
        unitPrice: 17.17,
        lineSubtotal: 51.5,
        extras: [],
      },
    ],
  },
  {
    id: "1048",
    code: "GW-1048",
    status: "entregado",
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    etaMin: 0,
    customerName: "Carlos Pérez",
    phone: "999000111",
    district: "San Isidro",
    address: "Calle Las Camelias 120",
    reference: "Recepción principal",
    deliveryType: "delivery",
    deliveryFee: 10,
    total: 27.8,
    notes: "",
    items: [
      {
        id: "1048-1",
        name: "Chaufa Clásico",
        itemNameSnapshot: "Chaufa Clásico",
        qty: 1,
        unitPrice: 17.8,
        lineSubtotal: 17.8,
        extras: [],
      },
    ],
  },
];

import type { EventLead } from "@/types/eventLead.types";

export const mockEventLeads: EventLead[] = [
  {
    id: "201",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    contactName: "Ramiro Lopez",
    phone: "992113692",
    guestCount: 120,
    eventDate: "2026-04-22",
    location: "La Molina",
    chaufaChoice: "Chaufa Clásico",
    notes: "Evento corporativo. Requiere cotización formal.",
    status: "nuevo",
  },
  {
    id: "202",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    contactName: "Luciana Vega",
    phone: "987111222",
    guestCount: 60,
    eventDate: "2026-05-10",
    location: "Surco",
    chaufaChoice: "Chaufa Aeropuerto",
    notes: "Interesada en propuesta para cumpleaños.",
    status: "cotizado",
  },
  {
    id: "203",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contactName: "Carlos Pérez",
    phone: "999000111",
    guestCount: 90,
    eventDate: "2026-05-18",
    location: "San Borja",
    chaufaChoice: "Mixto",
    notes: "Pidió llamada de seguimiento.",
    status: "contactado",
  },
  {
    id: "204",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    contactName: "María Fernanda",
    phone: "965444888",
    guestCount: 150,
    eventDate: "2026-06-01",
    location: "Miraflores",
    chaufaChoice: "Chaufa + Wantix",
    notes: "Cliente con alta intención de cierre.",
    status: "cerrado",
  },
];
