import type { Order } from "@/types/order.types";

export const mockOrders: Order[] = [
  {
    id: 1051,
    code: "GW-1051",
    status: "nuevo",
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    etaMin: 40,
    customerName: "Ramiro Lopez",
    phone: "992113692",
    district: "San Borja",
    address: "Av. Javier Prado 2450",
    reference: "Frente a la estación",
    deliveryFee: 10,
    total: 52.8,
    notes: "Sin cebolla en uno de los platos",
    items: [
      { name: "Chaufa Clásico", qty: 2, extras: ["Ají aparte"] },
      { name: "Wantix", qty: 4, extras: [] },
    ],
  },
  {
    id: 1050,
    code: "GW-1050",
    status: "preparacion",
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    etaMin: 35,
    customerName: "Luciana Vega",
    phone: "987111222",
    district: "Surco",
    address: "Calle Los Álamos 410",
    reference: "Portón negro",
    deliveryFee: 10,
    total: 43.9,
    notes: "Llamar al llegar",
    items: [
      { name: "Chaufa Aeropuerto", qty: 1, extras: ["Extra pollo", "Sillao aparte"] },
      { name: "Wantix", qty: 2, extras: [] },
    ],
  },
  {
    id: 1049,
    code: "GW-1049",
    status: "listo",
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    etaMin: 30,
    customerName: "María Fernanda",
    phone: "965444888",
    district: "Miraflores",
    address: "Av. Benavides 1880",
    reference: "Torre B, dpto. 602",
    deliveryFee: 10,
    total: 61.5,
    notes: "Agregar cubiertos",
    items: [{ name: "Chaufa Clásico", qty: 3, extras: [] }],
  },
  {
    id: 1048,
    code: "GW-1048",
    status: "entregado",
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    etaMin: 0,
    customerName: "Carlos Pérez",
    phone: "999000111",
    district: "San Isidro",
    address: "Calle Las Camelias 120",
    reference: "Recepción principal",
    deliveryFee: 10,
    total: 27.8,
    notes: "",
    items: [{ name: "Chaufa Clásico", qty: 1, extras: [] }],
  },
];

import type { EventLead } from "@/types/eventLead.types";

export const mockEventLeads: EventLead[] = [
  {
    id: 201,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    contactName: "Ramiro Lopez",
    phone: "992113692",
    guestCount: 120,
    eventDate: "2026-04-22",
    location: "La Molina",
    chaufaChoice: "Chaufa Clásico",
    notes: "Evento corporativo. Requiere cotización formal.",
    status: "nuevo",
  },
  {
    id: 202,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    contactName: "Luciana Vega",
    phone: "987111222",
    guestCount: 60,
    eventDate: "2026-05-10",
    location: "Surco",
    chaufaChoice: "Chaufa Aeropuerto",
    notes: "Interesada en propuesta para cumpleaños.",
    status: "cotizado",
  },
  {
    id: 203,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contactName: "Carlos Pérez",
    phone: "999000111",
    guestCount: 90,
    eventDate: "2026-05-18",
    location: "San Borja",
    chaufaChoice: "Mixto",
    notes: "Pidió llamada de seguimiento.",
    status: "contactado",
  },
  {
    id: 204,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    contactName: "María Fernanda",
    phone: "965444888",
    guestCount: 150,
    eventDate: "2026-06-01",
    location: "Miraflores",
    chaufaChoice: "Chaufa + Wantix",
    notes: "Cliente con alta intención de cierre.",
    status: "cerrado",
  },
];